# Generated by Django 3.2.2 on 2021-05-18 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('cod_catg', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_catg', models.CharField(max_length=50)),
            ],
        ),
    ]
