# Generated by Django 3.2.2 on 2021-05-18 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caos_news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('nombre_not', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('fecha_not', models.DateField()),
                ('redac', models.TextField()),
            ],
        ),
    ]
