# Generated by Django 3.2.2 on 2021-05-18 06:45

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('caos_news', '0002_noticia'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='categoria',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='caos_news.categoria'),
            preserve_default=False,
        ),
    ]
