# Generated by Django 3.2.2 on 2021-05-18 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caos_news', '0005_noticia_categoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noticia',
            name='categoria',
        ),
    ]
