# Generated by Django 3.2.2 on 2021-05-18 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caos_news', '0010_alter_noticia_categoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noticia',
            name='categoria',
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
        migrations.DeleteModel(
            name='Noticia',
        ),
    ]
