# Generated by Django 3.2.2 on 2021-05-18 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('caos_news', '0011_auto_20210518_0310'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('cod_catg', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_catg', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('nombre_not', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('fecha_not', models.DateField()),
                ('redac', models.TextField()),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caos_news.categoria')),
            ],
        ),
    ]
