# Generated by Django 3.2.2 on 2021-05-20 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caos_news', '0012_categoria_noticia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentarios',
            fields=[
                ('cod_coment', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_c', models.CharField(max_length=25)),
                ('apellido_c', models.CharField(max_length=25)),
                ('mail_c', models.EmailField(max_length=254)),
                ('coment', models.TextField()),
            ],
        ),
    ]
