# Generated by Django 3.2.2 on 2021-05-21 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caos_news', '0013_comentarios'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='img_not',
            field=models.ImageField(null=True, upload_to='noticias'),
        ),
    ]
