# Generated by Django 3.2.2 on 2021-05-21 05:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caos_news', '0014_noticia_img_not'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='fecha_not',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
