# Generated by Django 3.2.2 on 2021-05-26 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caos_news', '0015_alter_noticia_fecha_not'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='autor',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
