# Generated by Django 3.2.2 on 2021-05-26 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caos_news', '0016_noticia_autor'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='publicar',
            field=models.BooleanField(default=False),
        ),
    ]
