# Generated by Django 3.2.2 on 2021-06-15 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caos_news', '0020_noticia_comentario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='comentario',
            field=models.CharField(default='Sin observaciones', max_length=300, null=True),
        ),
    ]
