# Generated by Django 3.2.2 on 2021-06-15 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caos_news', '0021_alter_noticia_comentario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Galeria',
            fields=[
                ('cod_img', models.AutoField(primary_key=True, serialize=False)),
                ('imagen', models.ImageField(null=True, upload_to='galeria')),
            ],
        ),
    ]
