# Generated by Django 3.2.2 on 2021-06-15 23:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('caos_news', '0022_galeria'),
    ]

    operations = [
        migrations.AddField(
            model_name='galeria',
            name='not_gal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='caos_news.noticia'),
        ),
    ]
