# Generated by Django 3.2.2 on 2021-06-16 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caos_news', '0023_galeria_not_gal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='comentario',
            field=models.TextField(default='Sin observaciones', null=True),
        ),
    ]
